#!/bin/bash

# escape our pants off so that colorized prompts wont break line breaking
GREEN="\[\e[32m\]"
WHITE="\[\e[1;37m\]"
BOLD="\[\e[1m\]"
RED="\[\e[1;31m\]"
RESET="\[\e[m\]"

export GREEN
export WHITE
export BOLD
export RESET

# Constants

# functions to get git status

parse_git_branch () {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

parse_git_tag () {
    git describe --tags 2> /dev/null
}

parse_git_branch_or_tag() {
    local OUT="$(parse_git_branch)"
    if [ "$OUT" == " ((no branch))" ]; then
	OUT="($(parse_git_tag))";
    fi
    echo $OUT
}

# dont display user@host if local user at localhost

if [ $SSH_TTY ]; then
    export PS1="[\u@\h \W]${BOLD}\$(parse_git_branch_or_tag)${RESET}${GREEN}$ ${RESET}"
else
    export PS1="[\w]${BOLD}\$(parse_git_branch_or_tag)${RESET}${GREEN}$ ${RESET}"
fi
